run:
  go: '1.22'
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/jwill9999/scaffold-go
  gosec:
    excludes:
      - G204  # Subprocess launched with a potential tainted input or cmd arguments

issues:
  exclude:
    - "G404: Use of weak random number generator"
  exclude-dirs:
    - vendor
    - testdata
  exclude-files:
    - ".*_test\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
  max-issues-per-linter: 0
  max-same-issues: 0 