groups:
  - name: application
    rules:
      - alert: HighRequestLatency
        expr: http_request_duration_seconds{quantile="0.9"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "High request latency detected (> 1s at 90th percentile)"
          value: "{{ $value }}"
          runbook: "https://wiki.example.com/runbooks/high-latency"

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          description: "Error rate is above 5% ({{ $value | humanizePercentage }})"
          value: "{{ $value }}"
          runbook: "https://wiki.example.com/runbooks/high-error-rate"

  - name: resources
    rules:
      - alert: HighCPUUsage
        expr: avg(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "Container CPU usage is above 80%"
          value: "{{ $value | humanizePercentage }}"
          runbook: "https://wiki.example.com/runbooks/high-cpu"

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes / container_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "Container memory usage is above 90%"
          value: "{{ $value | humanizePercentage }}"
          runbook: "https://wiki.example.com/runbooks/high-memory"

  - name: database
    rules:
      - alert: PostgresHighConnections
        expr: pg_stat_activity_count > pg_settings_max_connections * 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "PostgreSQL connection count is above 80% of max connections"
          value: "{{ $value }}"
          runbook: "https://wiki.example.com/runbooks/postgres-connections"

      - alert: PostgresSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname!=""}[1m]) > 30
        for: 2m
        labels:
          severity: warning
        annotations:
          description: "PostgreSQL queries taking longer than 30 seconds detected"
          value: "{{ $value }}s"
          runbook: "https://wiki.example.com/runbooks/postgres-slow-queries" 