name: PR Validation

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate commits
        run: |
          # Get the commits in the PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git log --format=%B --no-merges ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | \
            npx commitlint --config commitlint.config.js
          fi

      - name: Check for merge conflicts
        run: |
          if grep -r "^<<<<<<< " --include="*.go" .; then
            echo "Merge conflicts detected in Go files"
            exit 1
          fi
          echo "✅ No merge conflicts detected"
