name: Code Quality

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

permissions:
  contents: read

jobs:
  # Call the linting workflow
  code-quality:
    uses: ./.github/workflows/linting.yml

  # Call the testing workflow
  tests:
    uses: ./.github/workflows/testing.yml
