name: Quality

on:
  push:
    branches:
      - main
      - develop
      - staging
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches: ["develop", "main", "staging"]

jobs:
  quality:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.5

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Run Tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
