name: Security

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches: ["develop", "main"]
  schedule:
    - cron: "0 0 * * 1" # Run weekly on Mondays

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true

  dependency-check:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true

      - name: Install nancy
        run: go install github.com/sonatype-nexus-community/nancy@latest

      - name: Generate go list
        run: go list -json -deps ./... > go-list.json

      - name: Check dependencies with nancy
        run: cat go-list.json | nancy sleuth --output json > nancy-results.json

      - name: Upload nancy results
        uses: actions/upload-artifact@v4
        with:
          name: nancy-results
          path: nancy-results.json
