name: Run Tests

on:
  push:
    branches: ["develop", "main", "staging"]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches: ["develop", "main", "staging"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: npm run test:ci
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable"

      - name: Generate HTML coverage report
        run: npm run test:html

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./test-output/cover.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-output/test-report.json
            test-output/cover.out
            test-output/coverage.html
          retention-days: 7
